/**
 * Tokens de inyección de dependencias para los repositorios del dominio.
 * Se usan con @Inject(REPOSITORY_TOKENS.TENANT) en los use cases.
 * Mantiene el dominio desacoplado de NestJS: los tokens son strings simples.
 */
export const REPOSITORY_TOKENS = {
  TENANT: 'TENANT_REPOSITORY',
  FISCAL_PROFILE: 'FISCAL_PROFILE_REPOSITORY',
  POINT_OF_SALE: 'POINT_OF_SALE_REPOSITORY',
  CUSTOMER: 'CUSTOMER_REPOSITORY',
  FISCAL_DOCUMENT: 'FISCAL_DOCUMENT_REPOSITORY',
  FISCAL_AUTHORIZATION: 'FISCAL_AUTHORIZATION_REPOSITORY',
  FISCAL_EVENT: 'FISCAL_EVENT_REPOSITORY',
  TENANT_CERTIFICATE: 'TENANT_CERTIFICATE_REPOSITORY',
  ACCESS_TICKET: 'ACCESS_TICKET_REPOSITORY',
  IDEMPOTENCY: 'IDEMPOTENCY_REPOSITORY',
} as const;
